## Numpy Indexing & Selection
(Adopted from Udemy Course, *Python for Data Science and Machine Learning Bootcamp* by Jose Portilla)

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8] # like indexing a list

8

**Slice Notation**

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Broacasting

In [8]:
arr[0:5] = 100000
arr

array([100000, 100000, 100000, 100000, 100000,      5,      6,      7,
            8,      9,     10])

**Pseudo Copy**

In [11]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_arr[:] = 10000
slice_arr

array([10000, 10000, 10000, 10000, 10000, 10000])

In [15]:
# however
arr

array([10000, 10000, 10000, 10000, 10000, 10000,     6,     7,     8,
           9,    10])

I call this Pseudo Copying, other also refers to it as shallow copying.

This happens because "slice_arr" and "arr" shares a same memory location, they are essentially the same variable with different names.

**How to copy then?**

In [17]:
arr_copy = arr.copy()
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000,     6,     7,     8,
           9,    10])

In [18]:
arr_copy[0:5] = 999
arr_copy

array([  999,   999,   999,   999,   999, 10000,     6,     7,     8,
           9,    10])

In [20]:
arr

array([10000, 10000, 10000, 10000, 10000, 10000,     6,     7,     8,
           9,    10])

## 2-D Arrays

In [3]:
arr_2d = np.array([[5,20,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 20, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
row = 0
column = 0
arr_2d[row][column]

5

In [5]:
arr_2d[row]

array([ 5, 20, 15])

In [8]:
arr_2d[:,column].reshape(3,1)

array([[ 5],
       [20],
       [35]])

In [26]:
# alternatively
arr_2d[row, column]

5

### Conditional Selection

In [27]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [32]:
arr[arr<3]

array([1, 2])