## Numpy Arrays

(Adopted from Udemy Course, *Python for Data Science and Machine Learning Bootcamp* by Jose Portilla)

#### Creating Arrays

**Using lists**

In [1]:
import numpy as np

In [2]:
ls = [1,2,3]
arr = np.array(ls)
arr

array([1, 2, 3])

In [3]:
# 2 dimensional arrays
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Notice the 2 squarely brackets to indicate this is a 2 dimensional array

**Using numpy directly**

In [5]:
np.arange(0,10) # just like range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(3) # pass in a number, one dimensional

array([0., 0., 0.])

In [8]:
np.zeros((3,3)) # pass in a tuple, multidimensional

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
np.linspace(1,5,50) # 50 evenly spaced points

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [13]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random numbers

**Uniform Distributions**

In [14]:
np.random.rand(5) # from uniform distribution from 0 to 1

array([0.66111528, 0.85442425, 0.36518287, 0.44832417, 0.59983944])

In [15]:
np.random.rand((5,5)) # note do NOT pass in tuple

TypeError: 'tuple' object cannot be interpreted as an integer

In [17]:
np.random.rand(5,5)

array([[0.21627737, 0.98031249, 0.94800651, 0.65656994, 0.83634858],
       [0.04574996, 0.93601643, 0.62993078, 0.88423421, 0.40045853],
       [0.52065334, 0.02031276, 0.94325643, 0.67492869, 0.42314298],
       [0.6397933 , 0.42619562, 0.48496281, 0.05945563, 0.85894151],
       [0.80974084, 0.31658502, 0.0269233 , 0.3095878 , 0.62835824]])

**Normal (Gaussian Distribution)**

In [18]:
# standard normal distribution
np.random.randn(10)

array([-0.50688765,  0.2414528 , -0.66571356, -1.87865842, -0.52932104,
       -1.74940518,  0.88918151,  1.13649779,  0.85591422, -1.63186129])

**Randome integers**

In [19]:
np.random.randint(1,100) # note low is inclusive, high is exclusive

97

In [20]:
np.random.randint(1,100, 10)

array([21, 61, 44, 62, 93, 81, 20, 72, 10, 98])

**Useful array features**

In [21]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ran_arr = np.random.randint(0,50,10)
ran_arr

array([14, 21, 47, 24, 40, 44, 40, 24, 28, 10])

In [23]:
# reshape - giving an 1-d array a new dimension

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.reshape(5,6) # need to match the totoal numbers

ValueError: cannot reshape array of size 25 into shape (5,6)

In [26]:
# finding maximum, minimum, and corresponding indices

In [27]:
ran_arr.max()

47

In [28]:
ran_arr.min()

10

In [29]:
ran_arr

array([14, 21, 47, 24, 40, 44, 40, 24, 28, 10])

In [30]:
ran_arr.argmax() # find location of maximum

2

In [31]:
ran_arr.argmin()

9

In [32]:
# dimension of arrays

In [33]:
arr.shape

(25,)

In [34]:
ran_arr.shape

(10,)

In [35]:
arr.reshape(5,5).shape

(5, 5)

In [36]:
# data types in an array

In [37]:
arr.dtype

dtype('int32')

In [38]:
# save some typing
from numpy.random import randint
randint(2,10)

9